"""Target languages a Mongolian learner can study.

The learner base and all guidance stay Mongolian — the *target language* is
what Sarah speaks, corrects, and scores. Content per language is generated by
the LLM at runtime (see coach.localize_scenario), so adding a language here is
enough to offer it end to end.

`stt` is the ISO code passed to Grok STT for number/unit formatting; `None`
means let STT auto-detect (Chinese isn't in the STT formatting list, but its
speech still transcribes). All languages use the same warm voice.
"""

TARGET_LANGS = {
    "en": {"name_en": "English",  "name_mn": "Англи хэл",   "native": "English", "flag": "🇬🇧", "stt": "en",
           "roman": None},
    "ko": {"name_en": "Korean",   "name_mn": "Солонгос хэл", "native": "한국어",   "flag": "🇰🇷", "stt": "ko",
           "roman": "Revised Romanization (e.g. 소녀 -> sonyeo)"},
    "zh": {"name_en": "Chinese (Mandarin)", "name_mn": "Хятад хэл", "native": "中文", "flag": "🇨🇳", "stt": None,
           "roman": "Hanyu Pinyin with tone marks (e.g. 你好 -> nǐ hǎo)"},
    "ja": {"name_en": "Japanese", "name_mn": "Япон хэл",     "native": "日本語",  "flag": "🇯🇵", "stt": "ja",
           "roman": "Hepburn romaji (e.g. こんにちは -> konnichiwa)"},
}
DEFAULT_LANG = "en"


def lang_meta(code: str) -> dict:
    return TARGET_LANGS.get(code, TARGET_LANGS[DEFAULT_LANG])


# ---- native (platform) languages: what the UI and coaching feedback use ----
# 'mn'  = Mongolian in Cyrillic (Mongolia)
# 'mnt' = Mongolian in traditional script (Inner Mongolia, ᠮᠣᠩᠭᠣᠯ ᠪᠢᠴᠢᠭ)
NATIVE_LANGS = {
    "mn": {
        "name": "Mongolian (Cyrillic)",
        "prompt": "Mongolian in CYRILLIC script",
    },
    "mnt": {
        "name": "Mongolian (traditional script)",
        "prompt": ("Mongolian in TRADITIONAL MONGOLIAN SCRIPT (Hudum bichig, "
                   "Unicode Mongolian block, e.g. ᠰᠠᠶᠢᠨ ᠪᠠᠶᠢᠨ᠎ᠠ ᠤᠤ) — never Cyrillic"),
    },
}
DEFAULT_NATIVE = "mn"


def native_of(user) -> str:
    try:
        if user is not None and "native_lang" in user.keys():
            v = user["native_lang"]
            if v in NATIVE_LANGS:
                return v
    except Exception:
        pass
    return DEFAULT_NATIVE


def native_prompt(code: str) -> str:
    return NATIVE_LANGS.get(code, NATIVE_LANGS[DEFAULT_NATIVE])["prompt"]


def roman_for(target_lang: str, native: str) -> str | None:
    """Pronunciation-aid scheme. Cyrillic-Mongolia users get Latin romanization
    (pinyin/romaja/romaji, none for English). Inner Mongolian users read Chinese,
    not Latin — they get Chinese-character phonetic transcription instead
    (except Chinese itself, where pinyin IS the Chinese standard)."""
    meta = lang_meta(target_lang)
    if native == "mnt":
        if target_lang == "zh":
            return meta["roman"]
        return ("Chinese-character phonetic approximation of the pronunciation, "
                "the way Chinese textbooks transcribe foreign sounds "
                "(e.g. 'Nice to meet you' -> 奈斯·图·米特·尤; 감사합니다 -> 卡姆萨哈姆尼达)")
    return meta["roman"]


def target_of(user) -> str:
    """The user's chosen study language, defaulting to English (and tolerating
    rows created before the column existed)."""
    try:
        if user is not None and "target_lang" in user.keys():
            v = user["target_lang"]
            if v in TARGET_LANGS:
                return v
    except Exception:
        pass
    return DEFAULT_LANG
