"""Target languages a Mongolian learner can study.

The learner base and all guidance stay Mongolian — the *target language* is
what Sarah speaks, corrects, and scores. Content per language is generated by
the LLM at runtime (see coach.localize_scenario), so adding a language here is
enough to offer it end to end.

`stt` is the ISO code passed to Grok STT for number/unit formatting; `None`
means let STT auto-detect (Chinese isn't in the STT formatting list, but its
speech still transcribes). All languages use the same warm voice.
"""

TARGET_LANGS = {
    "en": {"name_en": "English",  "name_mn": "Англи хэл",   "native": "English", "flag": "🇬🇧", "stt": "en",
           "roman": None},
    "ko": {"name_en": "Korean",   "name_mn": "Солонгос хэл", "native": "한국어",   "flag": "🇰🇷", "stt": "ko",
           "roman": "Revised Romanization (e.g. 소녀 -> sonyeo)"},
    "zh": {"name_en": "Chinese (Mandarin)", "name_mn": "Хятад хэл", "native": "中文", "flag": "🇨🇳", "stt": None,
           "roman": "Hanyu Pinyin with tone marks (e.g. 你好 -> nǐ hǎo)"},
    "ja": {"name_en": "Japanese", "name_mn": "Япон хэл",     "native": "日本語",  "flag": "🇯🇵", "stt": "ja",
           "roman": "Hepburn romaji (e.g. こんにちは -> konnichiwa)"},
}
DEFAULT_LANG = "en"


def lang_meta(code: str) -> dict:
    return TARGET_LANGS.get(code, TARGET_LANGS[DEFAULT_LANG])


def target_of(user) -> str:
    """The user's chosen study language, defaulting to English (and tolerating
    rows created before the column existed)."""
    try:
        if user is not None and "target_lang" in user.keys():
            v = user["target_lang"]
            if v in TARGET_LANGS:
                return v
    except Exception:
        pass
    return DEFAULT_LANG
