"""Scenario bank for daily micro-sessions.

Each scenario: Mongolian setup, the coach's English opener with Mongolian
translation, and a model answer (EN + MN) the learner can read aloud and
adapt — beginners should never face a question they can't answer.
"""
from dataclasses import dataclass

from .config import config


@dataclass(frozen=True)
class Scenario:
    id: str
    level: str          # beginner | intermediate | advanced
    title_mn: str
    setup_mn: str
    opener_en: str
    opener_mn: str      # translation of the opener
    example_en: str     # model answer the learner reads aloud / adapts
    example_mn: str     # its Mongolian meaning
    focus: str          # what the LLM should listen for


SCENARIOS: list[Scenario] = [
    # ---------- onboarding placement (first session only; never in rotation) ----------
    Scenario(
        id="placement",
        level="beginner",
        title_mn="Танилцах яриа",
        setup_mn="Сара таныг мэдэж авч, түвшинг тань тогтооно. Чөлөөтэй яриарай — энэ шалгалт биш!",
        opener_en=f"Hi! I'm {config.coach_name_en}, your speaking coach. I'd love to get to know you! What's your name, and what do you do?",
        opener_mn=f"Сайн уу! Би {config.coach_name_mn}, таны ярианы дасгалжуулагч. Тантай танилцмаар байна! Таныг хэн гэдэг вэ, юу хийдэг вэ?",
        example_en="My name is Bat. I work in an office. I want to speak better.",
        example_mn="Намайг Бат гэдэг. Би оффист ажилладаг. Илүү сайн ярьж сурмаар байна.",
        focus="get-to-know-you: name, job, family, interests, why they are learning; assess level from their answers",
    ),
    # ---------- beginner ----------
    Scenario(
        id="intro",
        level="beginner",
        title_mn="Өөрийгөө танилцуулах",
        setup_mn="Та шинэ хүнтэй танилцаж байна.",
        opener_en=f"Hi! I'm {config.coach_name_en}. Nice to meet you! What's your name, and what do you do?",
        opener_mn=f"Сайн уу! Би {config.coach_name_mn}. Танилцахад таатай байна! Таныг хэн гэдэг вэ, юу хийдэг вэ?",
        example_en="My name is Bat. I'm a student. I like basketball and music.",
        example_mn="Намайг Бат гэдэг. Би оюутан. Би сагсан бөмбөг, хөгжимд дуртай.",
        focus="self-introduction: name, job/study, hobbies; present simple",
    ),
    Scenario(
        id="coffee",
        level="beginner",
        title_mn="Кофе захиалах",
        setup_mn="Та кафед байна. Кофе болон идэх зүйл захиалаарай.",
        opener_en="Hello, welcome to Blue Sky Coffee! What can I get for you today?",
        opener_mn="Сайн байна уу, Blue Sky кофе шопт тавтай морил! Танд юу авч өгөх вэ?",
        example_en="One latte, please. And one cookie. For here.",
        example_mn="Нэг латте авъя. Бас нэг жигнэмэг. Энд ууна.",
        focus="ordering: I'd like..., size, here or to go, polite requests",
    ),
    Scenario(
        id="taxi",
        level="beginner",
        title_mn="Такси дуудах",
        setup_mn="Та таксинд суулаа. Хаашаа явахаа хэлж, үнийг асуугаарай.",
        opener_en="Good afternoon! Where would you like to go?",
        opener_mn="Өдрийн мэнд! Та хаашаа явах вэ?",
        example_en="To the State Department Store, please. How much is it?",
        example_mn="Улсын их дэлгүүр рүү явъя. Хэд болох вэ?",
        focus="directions, asking price, numbers",
    ),
    Scenario(
        id="shopping",
        level="beginner",
        title_mn="Дэлгүүрт үнэ асуух",
        setup_mn="Та дэлгүүрт хувцас үзэж байна. Үнэ, өнгө, хэмжээг нь асуугаарай.",
        opener_en="Hi there! Can I help you find anything?",
        opener_mn="Сайн байна уу! Танд юм олоход туслах уу?",
        example_en="How much is this T-shirt? Do you have black?",
        example_mn="Энэ футболк хэд вэ? Хар өнгөтэй нь бий юу?",
        focus="how much, sizes, colors, do you have...",
    ),
    Scenario(
        id="weekend",
        level="beginner",
        title_mn="Амралтын өдрийн төлөвлөгөө",
        setup_mn="Найз тань таны амралтын өдрийн төлөвлөгөөг асууж байна.",
        opener_en="Hey! Do you have any plans for the weekend?",
        opener_mn="Хөөе! Амралтын өдрөөр ямар нэг төлөвлөгөө бий юу?",
        example_en="Yes! On Saturday, I will see my parents. On Sunday, I will watch a movie.",
        example_mn="Тийм! Бямбад эцэг эхтэйгээ уулзана. Ням гарагт кино үзнэ.",
        focus="future plans: going to / will, days, activities",
    ),
    Scenario(
        id="restaurant",
        level="beginner",
        title_mn="Хоол захиалах",
        setup_mn="Та рестораны ширээнд сууж байна. Хоол, ундаа захиалаарай.",
        opener_en="Good evening! Here's the menu. Are you ready to order?",
        opener_mn="Оройн мэнд! Энэ таны цэс. Захиалахад бэлэн үү?",
        example_en="Yes. I'd like the beef soup and a green salad, please.",
        example_mn="Тийм ээ. Би үхрийн махтай шөл, ногооны салат авъя.",
        focus="ordering a meal: I'd like..., sides, polite requests",
    ),
    Scenario(
        id="directions",
        level="beginner",
        title_mn="Замаа асуух",
        setup_mn="Та гудамжинд төөрчихлөө. Хүнээс зам асуугаарай.",
        opener_en="Hi, you look a bit lost. Can I help you?",
        opener_mn="Сайн байна уу, та төөрсөн бололтой. Танд туслах уу?",
        example_en="Yes, thank you. How do I get to the train station?",
        example_mn="Тийм ээ, баярлалаа. Галт тэрэгний буудал руу яаж очих вэ?",
        focus="asking the way: how do I get to..., left/right/straight",
    ),
    Scenario(
        id="family",
        level="beginner",
        title_mn="Гэр бүлээ танилцуулах",
        setup_mn="Найз тань таны гэр бүлийн тухай асууж байна.",
        opener_en="So, tell me about your family. Do you have any brothers or sisters?",
        opener_mn="За, гэр бүлийнхээ тухай яриач. Чамд ах, эгч, дүү бий юу?",
        example_en="Yes, I have one older brother and one younger sister. My parents live in the countryside.",
        example_mn="Тийм, надад нэг ах, нэг дүү бий. Аав ээж минь хөдөө амьдардаг.",
        focus="family members, have/has, simple present",
    ),
    Scenario(
        id="market",
        level="beginner",
        title_mn="Захаас худалдан авах",
        setup_mn="Та зах дээр байна. Жимс, ногоо худалдаж аваарай.",
        opener_en="Hello! These apples are very fresh today. How many would you like?",
        opener_mn="Сайн байна уу! Өнөөдөр энэ алим их шинэхэн. Хэдийг авах вэ?",
        example_en="One kilo, please. And how much are the tomatoes?",
        example_mn="Нэг кило авъя. Улаан лооль хэд вэ?",
        focus="quantities, kilos, how much, this/these",
    ),
    Scenario(
        id="phone_appt",
        level="beginner",
        title_mn="Утсаар цаг товлох",
        setup_mn="Та үсчинд утсаар цаг авах гэж байна.",
        opener_en="Good morning, Sunrise Salon. How can I help you?",
        opener_mn="Өглөөний мэнд, Sunrise салон байна. Танд яаж туслах вэ?",
        example_en="Hello, I'd like to book a haircut for tomorrow afternoon, please.",
        example_mn="Сайн байна уу, маргааш үдээс хойш үс засуулах цаг авмаар байна.",
        focus="phone politeness, booking, days and times",
    ),
    Scenario(
        id="daily_routine",
        level="beginner",
        title_mn="Өдрийн хуваарь",
        setup_mn="Багш тань таны өдөр тутмын амьдралыг асууж байна.",
        opener_en="What does a normal day look like for you? When do you usually wake up?",
        opener_mn="Таны энгийн өдөр ямар байдаг вэ? Ер нь хэдэн цагт босдог вэ?",
        example_en="I usually wake up at seven. I go to work at nine and come home at six.",
        example_mn="Би ихэвчлэн долоон цагт босдог. Есөн цагт ажилдаа явж, зургаан цагт гэртээ ирдэг.",
        focus="daily routine, telling time, present simple, frequency words",
    ),
    Scenario(
        id="weather_smalltalk",
        level="beginner",
        title_mn="Цаг агаарын тухай яриа",
        setup_mn="Та автобусны буудал дээр танихгүй хүнтэй ярьж байна.",
        opener_en="Brr, it's really cold today, isn't it?",
        opener_mn="Өө, өнөөдөр үнэхээр хүйтэн байна тээ?",
        example_en="Yes, very cold! I hope it gets warmer next week.",
        example_mn="Тийм, их хүйтэн! Дараа долоо хоногт дулаарна гэж найдаж байна.",
        focus="small talk, weather words, tag questions, hope",
    ),
    # ---------- intermediate ----------
    Scenario(
        id="job_interview",
        level="intermediate",
        title_mn="Ажлын ярилцлага",
        setup_mn="Та ажлын ярилцлагад орж байна. Туршлага, давуу талаа яриарай.",
        opener_en="Thanks for coming in today. Could you tell me a little about yourself and your experience?",
        opener_mn="Өнөөдөр ирсэнд баярлалаа. Өөрийнхөө тухай болон туршлагаасаа ярьж өгөхгүй юу?",
        example_en="Thank you for inviting me. I graduated from university two years ago, and I have been working as a sales assistant. I'm good at talking with customers.",
        example_mn="Урьсанд баярлалаа. Би хоёр жилийн өмнө их сургууль төгссөн, одоо борлуулалтын туслахаар ажиллаж байгаа. Би үйлчлүүлэгчидтэй харилцахдаа сайн.",
        focus="past experience, strengths, professional vocabulary, past tense",
    ),
    Scenario(
        id="hotel",
        level="intermediate",
        title_mn="Буудалд асуудал шийдэх",
        setup_mn="Таны буудлын өрөөний халаалт ажиллахгүй байна. Гомдол гаргаж, шийдэл хүсээрэй.",
        opener_en="Front desk, good evening. How can I help you?",
        opener_mn="Ресепшн байна, оройн мэнд. Танд яаж туслах вэ?",
        example_en="Good evening. I'm in room 305. The heating is not working and the room is very cold. Could you send someone to fix it, please?",
        example_mn="Оройн мэнд. Би 305 тоот өрөөнд байна. Халаалт ажиллахгүй, өрөө их хүйтэн байна. Засах хүн явуулж өгнө үү?",
        focus="polite complaints, explaining problems, requests",
    ),
    Scenario(
        id="doctor",
        level="intermediate",
        title_mn="Эмчид үзүүлэх",
        setup_mn="Та эмчид үзүүлж байна. Шинж тэмдгээ тайлбарлаарай.",
        opener_en="Hello, please have a seat. What seems to be the problem today?",
        opener_mn="Сайн байна уу, сууна уу. Өнөөдөр юу болоод байна вэ?",
        example_en="Hello, doctor. I have had a headache and a sore throat for three days. I also feel very tired.",
        example_mn="Сайн байна уу, эмч ээ. Гурав хоног толгой өвдөж, хоолой сөөж байна. Бас их ядарч байна.",
        focus="symptoms, duration (for/since), body vocabulary",
    ),
    Scenario(
        id="hometown",
        level="intermediate",
        title_mn="Төрсөн нутгаа дүрслэх (IELTS хэв маяг)",
        setup_mn="IELTS ярианы шалгалтын хэв маягаар: төрсөн нутгаа дүрслээрэй.",
        opener_en="Let's talk about where you're from. Can you describe your hometown for me?",
        opener_mn="Таны төрсөн нутгийн тухай ярилцъя. Нутгаа дүрсэлж өгөхгүй юу?",
        example_en="I'm from Ulaanbaatar, the capital of Mongolia. It's a busy city with about 1.5 million people. I love it because my family and friends live there, but the traffic is terrible.",
        example_mn="Би Монголын нийслэл Улаанбаатараас ирсэн. 1.5 сая орчим хүнтэй, завгүй хот. Гэр бүл, найзууд минь тэнд амьдардаг болохоор би хотдоо хайртай, гэхдээ замын түгжрэл нь аймшигтай.",
        focus="description, adjectives, giving reasons, extended answers",
    ),
    Scenario(
        id="opinion_city",
        level="intermediate",
        title_mn="Хотын амьдралын тухай санал бодол",
        setup_mn="Хотын амьдрал ба хөдөөний амьдралын аль нь дээр вэ? Саналаа хэлээрэй.",
        opener_en="Some people love city life, others prefer the countryside. What do you think?",
        opener_mn="Зарим хүн хотын амьдралд дуртай, зарим нь хөдөөг илүүд үздэг. Та юу гэж боддог вэ?",
        example_en="In my opinion, city life is better for young people because there are more jobs and schools. However, the countryside is quieter and the air is cleaner.",
        example_mn="Миний бодлоор залууст хотын амьдрал илүү тохиромжтой, учир нь ажил, сургууль олон. Гэхдээ хөдөө нам гүм, агаар нь цэвэр.",
        focus="opinions: I think/in my view, comparisons, because/so",
    ),
    Scenario(
        id="new_colleague",
        level="intermediate",
        title_mn="Шинэ хамт олонтой танилцах",
        setup_mn="Ажилдаа шинэ хамт олонтойгоо анх удаа тааралдлаа. Танилцаж яриа өрнүүлээрэй.",
        opener_en="Hi, you must be the new hire. I'm Alex, I work in marketing. How's your first week going?",
        opener_mn="Сайн уу, та шинэ ажилтан байх нь. Намайг Алекс гэдэг, маркетингт ажилладаг. Эхний долоо хоног чинь ямар байна?",
        example_en="Nice to meet you, Alex. It's going well, thanks. Everyone has been really helpful so far.",
        example_mn="Танилцахад таатай байна, Алекс. Сайхан байна, баярлалаа. Одоохондоо бүгд их тусархуу хандаж байна.",
        focus="workplace small talk, present perfect, describing experience",
    ),
    Scenario(
        id="describe_job",
        level="intermediate",
        title_mn="Ажлаа тайлбарлах",
        setup_mn="Танихгүй хүн таны ажил, компанийн тухай сонирхож байна.",
        opener_en="So what do you do? What kind of company do you work for?",
        opener_mn="Та ямар ажил хийдэг вэ? Ямар компанид ажилладаг вэ?",
        example_en="I work for a logistics company. I manage deliveries and make sure orders arrive on time.",
        example_mn="Би тээвэр логистикийн компанид ажилладаг. Хүргэлтийг зохион байгуулж, захиалга цагтаа хүрэхийг хариуцдаг.",
        focus="describing work, responsibilities, present simple, job vocabulary",
    ),
    Scenario(
        id="return_item",
        level="intermediate",
        title_mn="Бараа буцаах",
        setup_mn="Худалдаж авсан гутал тань эвдэрчихлээ. Дэлгүүрт буцааж, шийдэл хүсээрэй.",
        opener_en="Hi, welcome back. Is there a problem with your purchase?",
        opener_mn="Сайн байна уу, дахин тавтай морил. Худалдаж авсан бараанд тань асуудал гарав уу?",
        example_en="Yes, I bought these shoes last week, but the sole is already broken. Can I get a refund or an exchange?",
        example_mn="Тийм, би энэ гутлыг өнгөрсөн долоо хоногт авсан юм, гэтэл ул нь аль хэдийн эвдэрчихэж. Мөнгөө буцааж авах, эсвэл солиулж болох уу?",
        focus="complaints, refund/exchange, explaining a problem, polite requests",
    ),
    Scenario(
        id="trip_plan",
        level="intermediate",
        title_mn="Аялал төлөвлөх",
        setup_mn="Найзтайгаа хамт амралтаараа аялахаар төлөвлөж байна.",
        opener_en="I was thinking we could go somewhere for the long weekend. Where would you like to go?",
        opener_mn="Бид энэ урт амралтаар хаа нэгтээ явчихвал ямар вэ гэж бодож байлаа. Чи хаашаа явмаар байна?",
        example_en="That sounds great. How about the countryside? We could rent a car and leave on Friday morning.",
        example_mn="Гоё санаа байна. Хөдөө явбал яасан юм бэ? Машин түрээслээд, баасан гарагийн өглөө гарч болно.",
        focus="making plans, suggestions, could/how about, future",
    ),
    Scenario(
        id="it_support",
        level="intermediate",
        title_mn="Техникийн тусламж",
        setup_mn="Таны компьютер ажиллахаа больжээ. Тусламжийн ажилтанд асуудлаа тайлбарлаарай.",
        opener_en="IT support, this is Sam. What seems to be the problem?",
        opener_mn="Техникийн тусламж, Сэм байна. Ямар асуудал гарав?",
        example_en="Hi Sam. My laptop won't turn on. I pressed the power button, but nothing happens.",
        example_mn="Сайн уу, Сэм. Миний зөөврийн компьютер асахгүй байна. Асаах товчийг дарсан ч юу ч болохгүй байна.",
        focus="describing a problem, tech vocabulary, won't/doesn't, sequence",
    ),
    Scenario(
        id="bank",
        level="intermediate",
        title_mn="Банкинд үйлчлүүлэх",
        setup_mn="Та банкинд данс нээлгэх гэж байна. Ажилтнаас асуугаарай.",
        opener_en="Good afternoon. How can I help you today?",
        opener_mn="Өдрийн мэнд. Танд өнөөдөр яаж туслах вэ?",
        example_en="Hello. I'd like to open a savings account. What documents do I need to bring?",
        example_mn="Сайн байна уу. Би хадгаламжийн данс нээлгэмээр байна. Ямар бичиг баримт авчрах хэрэгтэй вэ?",
        focus="formal requests, banking vocabulary, what/which questions",
    ),
    # ---------- advanced ----------
    Scenario(
        id="negotiation",
        level="advanced",
        title_mn="Цалингийн хэлэлцээр",
        setup_mn="Та цалин нэмүүлэх хүсэлтээ менежертээ тайлбарлаж байна. Үндэслэлээ гаргаарай.",
        opener_en="You wanted to discuss your compensation. I have about ten minutes — what's on your mind?",
        opener_mn="Та цалингийн асуудлаар ярилцахыг хүссэн. Надад 10 минут байна — сонсъё.",
        example_en="Thank you for your time. Over the past year, I have taken on more responsibilities and my results have grown. Based on that, I would like to discuss a salary increase of about 15 percent.",
        example_mn="Цаг гаргасанд баярлалаа. Өнгөрсөн жил би илүү их үүрэг хариуцлага авч, үр дүн маань өссөн. Үүн дээр үндэслэн 15 хувийн цалингийн нэмэгдэл ярилцмаар байна.",
        focus="persuasion, hedging language, conditionals, professional register",
    ),
    Scenario(
        id="presentation",
        level="advanced",
        title_mn="Төслөө танилцуулах",
        setup_mn="Та багтаа шинэ төслийн санаагаа нэг минутад танилцуулж байна.",
        opener_en="Alright, the floor is yours — tell us about your idea.",
        opener_mn="За, таны ээлж — санаагаа танилцуулна уу.",
        example_en="Thank you. First, let me describe the problem: our customers wait too long for replies. My idea is a simple chatbot that answers common questions. Finally, this could save us about ten hours every week.",
        example_mn="Баярлалаа. Эхлээд асуудлыг хэлье: үйлчлүүлэгчид маань хариу хэт удаан хүлээдэг. Миний санаа бол түгээмэл асуултад хариулдаг энгийн чатбот. Эцэст нь энэ нь долоо хоногт арав орчим цаг хэмнэнэ.",
        focus="structuring: first/then/finally, problem-solution, signposting",
    ),
    Scenario(
        id="client_delay",
        level="advanced",
        title_mn="Хүргэлтийн саатлыг тайлбарлах",
        setup_mn="Захиалга хожимдож байна. Үйлчлүүлэгчид нөхцөл байдлыг тайлбарлаж, шийдэл санал болгоорой.",
        opener_en="Thanks for taking my call. I'm calling about my order — it was supposed to arrive yesterday and it still hasn't. What's going on?",
        opener_mn="Утсаа авсанд баярлалаа. Би захиалгынхаа талаар залгаж байна — өчигдөр ирэх ёстой байсан атлаа одоо болтол ирээгүй байна. Юу болоод байгаа юм бэ?",
        example_en="I completely understand your frustration, and I apologize for the delay. There was a customs issue, but your shipment has now cleared and will arrive by Thursday. I'll send you the tracking details right away.",
        example_mn="Таны бухимдлыг бүрэн ойлгож байна, саатуулсанд уучлаарай. Гаалийн асуудал гарсан юм, гэхдээ таны ачаа одоо гарсан бөгөөд пүрэв гараг гэхэд хүрнэ. Хяналтын дугаарыг тань яг одоо илгээе.",
        focus="apologizing, explaining, reassuring a client, professional register, conditionals",
    ),
    Scenario(
        id="team_feedback",
        level="advanced",
        title_mn="Хамтрагчдаа санал өгөх",
        setup_mn="Багийнхаа гишүүнд ажлынх нь талаар бүтээлч санал өгч байна.",
        opener_en="You wanted to chat about how the project went. I'd love to hear your honest thoughts on my part.",
        opener_mn="Та төсөл хэрхэн явсан талаар ярилцах гэсэн. Миний хийсэн хэсгийн талаар шударга бодлоо сонсмоор байна.",
        example_en="You did a great job on the design. One thing I'd suggest is sharing updates a bit earlier, so the team has more time to react. Overall, though, it was really solid work.",
        example_mn="Дизайны хувьд та маш сайн ажилласан. Нэг санал бол шинэчлэлээ жаахан эрт хуваалцвал баг илүү хугацаатай хариу үзүүлэх боломжтой болно. Ер нь бол үнэхээр чанартай ажил болсон.",
        focus="constructive feedback, softening language, suggestions, balancing praise and critique",
    ),
    Scenario(
        id="disagree_meeting",
        level="advanced",
        title_mn="Хуралд эелдэгээр эсэргүүцэх",
        setup_mn="Хурал дээр хамт олны санал таныхаас өөр байна. Саналаа эелдэгээр илэрхийлээрэй.",
        opener_en="So I think we should launch next month. Everyone seems to agree — what do you think?",
        opener_mn="Тэгэхээр бид дараа сард эхлүүлэх ёстой гэж бодож байна. Бүгд зөвшөөрч байгаа юм шиг байна — та юу гэж бодож байна?",
        example_en="I see the appeal of moving quickly, but I have some concerns. If we launch next month, we won't have time to test properly. Could we consider pushing it back two weeks?",
        example_mn="Хурдан хөдлөх нь сайхан гэдгийг ойлгож байна, гэхдээ надад санаа зовоосон зүйл бий. Хэрэв дараа сард эхлүүлбэл зөв туршиж үзэх хугацаа гарахгүй. Хоёр долоо хоногоор хойшлуулж болох болов уу?",
        focus="polite disagreement, hedging, giving reasons, making counter-proposals",
    ),
    Scenario(
        id="behavioral_interview",
        level="advanced",
        title_mn="Ярилцлага: хүнд нөхцөл",
        setup_mn="Ажлын ярилцлагад: тулгарч байсан хүнд нөхцөл, түүнийгээ хэрхэн шийдсэнээ ярина.",
        opener_en="Can you tell me about a time you faced a difficult challenge at work and how you handled it?",
        opener_mn="Ажил дээрээ хүнд бэрхшээлтэй тулгарч, түүнийгээ хэрхэн даван туулсан тухайгаа ярьж өгөх үү?",
        example_en="Sure. Last year, a key supplier failed at the last minute. I quickly found an alternative, negotiated a fair price, and we delivered on time. It taught me to always have a backup plan.",
        example_mn="За. Өнгөрсөн жил гол нийлүүлэгч маань сүүлийн мөчид дампуурсан. Би хурдан өөр хувилбар олж, боломжийн үнээр тохиролцоод, цагтаа хүргэсэн. Энэ надад үргэлж нөөц төлөвлөгөөтэй байхыг сургасан.",
        focus="STAR storytelling, past tenses, professional narrative, reflection",
    ),
]


def pick_scenario(level: str, sessions_done: int) -> Scenario:
    """Rotate deterministically through the user's level pool."""
    pool = [s for s in SCENARIOS if s.level == level and s.id != "placement"] or SCENARIOS
    return pool[sessions_done % len(pool)]


def by_id(scenario_id: str) -> Scenario:
    for s in SCENARIOS:
        if s.id == scenario_id:
            return s
    return SCENARIOS[0]
